server:
  port: 9090
spring:
  application: springBootKafka
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: com.springboot.kafka.trn.customserdes.CustomSerializer

    consumer:
      bootstrap-servers: localhost:9092
      group-id: kafka001
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.springboot.kafka.trn.customserdes.CustomDeserializer



springBootKafka:
  kafka:
    topic: firstKafkaTopic

